services:
  - type: web
    name: puppeteer-app
    env: docker
    buildCommand: docker build -t app .
    startCommand: docker run -p $PORT:3000 app
    envVars:
      - key: NODE_ENV
        value: production
    plan: standard
    scaling:
      minInstances: 1
      maxInstances: 3
    healthCheckPath: /
    disk:
      name: tmp
      mountPath: /tmp
      sizeGB: 1